customhost = "employee.cn3zttjufv2d.us-east-2.rds.amazonaws.com"
customuser = "ijudekelvin"
custompass = "ijudekelvin123"
customdb = "employee"
custombucket = "ijudekelvin"
customregion = "us-east-2"
